config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#home'
  get '/flat/:id', to: 'flats#flat', as: 'flat'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController

  def home
    # pegar os flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end

  def flat
    
    # vamos mostrar a info de um flat especifico
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    flats = JSON.parse(open(url).read)
    @flat1 = flats.find { |flat| flat['id'] == params['id'].to_i }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/flat.html.erb
<h1><%= @flat1['name'] %></h1>

<img src="<%= @flat1['imageUrl'] %>" alt="" height="200">

<%= link_to "back to home", root_path %>

app/views/flats/home.html.erb
<h1>Airbnb clone</h1>
<h2>This is the list of our flats:</h2>

<ul>
  <% @flats.each do |flat| %>
    <li> <%= link_to flat['name'], flat_path(id: flat['id']) %> </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone616</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>